### ISSUE TITLE
大佬功能都实现了完了吗？

### ISSUE THREAD

**Issue by Yakumo-Yukari** [hys1440248234/Developer-Forum#2]

**Comment by hys1440248234** [comment]
非大佬。没有做完，还在做。

**Comment by Yakumo-Yukari** [comment]
> 非大佬。没有做完，还在做。

目前完成了那些呢？

**Comment by hys1440248234** [comment]
应该做不完，看能完成多少就完成多少，现在只有文章列表的显示完成了。最近一直在找工作也没有写，下个月会加快进度的。

**Comment by hys1440248234** [comment]
> > 非大佬。没有做完，还在做。
> 
> 目前完成了那些呢？

应该做不完，看能完成多少就完成多少，现在只有文章列表的显示完成了。最近一直在找工作也没有写，下个月会加快进度的。
